### PR TITLE
Proposed layout changes

### PR DESCRIPTION
**Pull request by roydeanjr**
This layout is the preferred layout. Please consider updating to this layout or let me know what you think.
image

### CODE REVIEW

**Comment by ryanmitchell** [comment]
I made a couple of minor tweaks. Generally it all feels too compressed to me now, and isn't good from a UX / information hierarchy design viewpoint.

**Comment by roydeanjr** [comment]
> Yeah this looks good to me.
> 
> 1. Try changing 'notify_customer' => true to 'notify' => true - let me know if that works for you? 'notify_customer' => true is working ok on my side, and from looking at the code it should be right...
> 2. I've pushed  a change for this.
> 3. Not sure what you mean by renaming?
> 
> In terms of texting, it would be better to write another extension that sent texts on order status change - that way it would work universally. I could write something that would integrate with Twilio if you wanted to sponsor the development (https://www.twilio.com/sms/pricing/us)?

How much to sponsor development?
Is it a possibility to integrate into my mobile phone and make it send the message or maybe if a tablet that is LTE enabled can send a message? Just brain storming here.

**Comment by roydeanjr** [comment]
And renaming the extension to a name that better describes what the extension does. Running Order does not do that for me. The familiar name that I have seen is Kitchen Display, KDS or Order Processing, etc.

**Comment by ryanmitchell** [comment]
It would need to use a use an API to send the texts - using a local phone would be a nightmare to set up, and I've had enough pain with the printer extension! :) 

I don't mind renaming it - but I'm still unsure about releasing it to the marketplace as it means I need to support it.

**Comment by roydeanjr** [comment]
> It would need to use a use an API to send the texts - using a local phone would be a nightmare to set up, and I've had enough pain with the printer extension! :)
> 
> I don't mind renaming it - but I'm still unsure about releasing it to the marketplace as it means I need to support it.

I completely understand the support issue. If it is paid, support would be required. If it is free, isn't support an option? And the option is fulfilled only if it is paid for?

I am willing to provide first level support if that helps.

**Comment by ryanmitchell** [comment]
When it comes to this system people can be very demanding! I've had to do screenshares and all sorts on free extensions.

**Comment by roydeanjr** [comment]
> When it comes to this system people can be very demanding! I've had to do screenshares and all sorts on free extensions.

That sux! I am happy to compensate you. I did subscribe on opencollective to give Sam $25/mo. I posted a "shame on you" message for all to see if they review who is contributing to this solution. It is a great solution and should not be used for free by the world when it is put out there for the "greater good" of humanity. It makes me sad that people are like that!

**Comment by ryanmitchell** [comment]
Thats great - thanks for supporting him.

**Pull request merged**
