### PR TITLE
Changed from Summary to Detail

### PR DESCRIPTION
**Pull request by roydeanjr**
This update reflects what would be necessary for a Kitchen staff/chef to actually plate the dishes ordered. I added the menu options so the options selected by the customer are reflected in the details for each order. I also added buttons for updating the status of the order through the process after Received. Namely buttons for Preparation, Ready for Pickup and Complete.

### CODE REVIEW

**Comment by ryanmitchell** [comment]
I pushed some changes to make it more generic for people - if its to be released it can't use hard coded statuses etc

**Comment by roydeanjr** [comment]
Agree, did not know how to make it not.

RoyDean Leighton
At your service......

________________________________

**Comment by ryanmitchell** [comment]
I just used the colours from the theme. I could change it to use the status colours - hadn’t thought if that. I’ll look into it next week.

**Comment by ryanmitchell** [comment]
Ok here's a reskin into a card format like you mentioned.
Let me know what you think.

**Comment by roydeanjr** [comment]
Ok, I clicked on running order and get an error: Undefined index in Collection.php line 1290 at collection-_offsetGet(null) in Summary.php line 158. What is my resolution?


Cheers,

RoyDean Leighton, Jr.
https://facebook.com/RDQBBQ

https://rdqbbq.com<http://rdqbbq.com/>

https://instagram.com/RDQBBQ

<https://yelp.com/rdq-houston>https://www.yelp.com/biz/rdq-houston
https://twitter.com/RDQBBQ

________________________________

**Comment by roydeanjr** [comment]
Here is the whole ErrorException
(1/1) ErrorException

Undefined index:

in Collection.php line 1290
at HandleExceptions->handleError(8, 'Undefined index: ', '/opt/lampp/htdocs/rdqtest/vendor/laravel/framework/src/Illuminate/Support/Collection.php', 1290, array('key' => null))in Collection.php line 1290
at Collection->offsetGet(null)in Summary.php line 158
at Summary->renderResults()in index.php line 51
at include('/opt/lampp/htdocs/rdqtest/extensions/thoughtco/runningorder/views/summary/index.php')in ViewMaker.php line 203
at AdminController->makeFileContent('/opt/lampp/htdocs/rdqtest/extensions/thoughtco/runningorder/views/summary/index.php')in ViewMaker.php line 132
at AdminController->makeView('index')in AdminController.php line 210
at AdminController->execPageAction('index', array('index'))in AdminController.php line 172
at AdminController->remap('index', array())in Controller.php line 110
at Controller->runAdmin('thoughtco/runningorder/summary')
at call_user_func_array(array(object(Controller), 'runAdmin'), array('slug' => 'thoughtco/runningorder/summary'))in Controller.php line 54
at Controller->callAction('runAdmin', array('slug' => 'thoughtco/runningorder/summary'))in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch(object(Route), object(Controller), 'runAdmin')in Route.php line 219
at Route->runController()in Route.php line 176
at Route->run()in Router.php line 681
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in VerifyCsrfToken.php line 76
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CurrencyMiddleware.php line 33
at CurrencyMiddleware->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in LogUserLastSeen.php line 26
at LogUserLastSeen->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Localization.php line 40
at Localization->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in StartSession.php line 56
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in EncryptCookies.php line 66
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Router.php line 683
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 658
at Router->runRoute(object(Request), object(Route))in Router.php line 624
at Router->dispatchToRoute(object(Request))in CoreRouter.php line 20
at CoreRouter->dispatch(object(Request))in Kernel.php line 170
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 130
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in InjectDebugbar.php line 65
at InjectDebugbar->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in SaveSetting.php line 25
at SaveSetting->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in TransformsRequest.php line 21
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in CheckForMaintenanceMode.php line 63
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 171
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 105
at Pipeline->then(object(Closure))in Kernel.php line 145
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 110
at Kernel->handle(object(Request))in index.php line 53


Cheers,

RoyDean Leighton, Jr.
https://facebook.com/RDQBBQ

https://rdqbbq.com<http://rdqbbq.com/>

https://instagram.com/RDQBBQ

<https://yelp.com/rdq-houston>https://www.yelp.com/biz/rdq-houston
https://twitter.com/RDQBBQ

________________________________

**Comment by roydeanjr** [comment]
Ryan, interestingly the updates don't work on my local server, but they do work on my website test server (external and updated versions or server applications)

Is the error related to the version of php or mysql or something else?

And, the grid looks good, however if there are notes, the notes stretch across the whole page so i only get one order on that row. Can you limit the width of the order block to 1/3rd or 1/4th or add an option to select how many blocks the admin wants to set for the display?

Great work!


Cheers,

RoyDean Leighton, Jr.
https://facebook.com/RDQBBQ

https://rdqbbq.com<http://rdqbbq.com/>

https://instagram.com/RDQBBQ

<https://yelp.com/rdq-houston>https://www.yelp.com/biz/rdq-houston
https://twitter.com/RDQBBQ

________________________________

**Comment by roydeanjr** [comment]
And, now I am getting too picky!

Could you make the header section where the order summary info is have a background matching the current status of the order?
And, the text needs to be set larger. I can increase the size of the page using the browser, but that means everything grows. I don't really want that, but that would work to increase the size. If the size of the text is increased then the max number of block might need to drop to 2 or 3.

Those tweaks will make this a great extension and I think every install will want this capability since it provides processing functionality that is currently a bit cumbersome.

Thank you again for your great work! It does look great!


Cheers,

RoyDean Leighton, Jr.
https://facebook.com/RDQBBQ

https://rdqbbq.com<http://rdqbbq.com/>

https://instagram.com/RDQBBQ

<https://yelp.com/rdq-houston>https://www.yelp.com/biz/rdq-houston
https://twitter.com/RDQBBQ

________________________________

**Comment by roydeanjr** [comment]
And, maybe last, making the menu collapse would be great! Can that be copied from v2.1.1? or is it more complicated than that?


Cheers,

RoyDean Leighton, Jr.
https://facebook.com/RDQBBQ

https://rdqbbq.com<http://rdqbbq.com/>

https://instagram.com/RDQBBQ

<https://yelp.com/rdq-houston>https://www.yelp.com/biz/rdq-houston
https://twitter.com/RDQBBQ

________________________________

**Comment by ryanmitchell** [comment]
The error looks like its due to there being no ready status on your local install - or at least no colour associated with it.

I've pushed an update with modifications to the layout to fix it to be a 3 columns at most and increase the font sizes a little. They look good on my screen, and I wouldn't been keen to go any bigger. The status color is already there with teh border on the right hand side - its there for an indication, making it a background colour would be overwhelming.

**Comment by ryanmitchell** [comment]
As for the collapsing menu - thats one to take up with Sam I'm afraid.

**Comment by roydeanjr** [comment]
Thank you for doing all this work! I could not have gotten this far this quickly.

For the background color, this is what I had in mind:
[cid:32182db8-aa85-4911-860e-0c8389c8ef76]

Also, what do you think about getting the system to email or text the customer when the order changes status?

Cheers,

RoyDean Leighton, Jr.
https://facebook.com/RDQBBQ

https://rdqbbq.com<http://rdqbbq.com/>

https://instagram.com/RDQBBQ

<https://yelp.com/rdq-houston>https://www.yelp.com/biz/rdq-houston
https://twitter.com/RDQBBQ

________________________________

**Comment by ryanmitchell** [comment]
No problem. 

Your attachment didn’t come through so I can’t see it. 

Updating the Status should fire any customer emails - if not let me know as that‘s what I would expect and ill raise it with Sam if it doesn’t.

**Comment by ryanmitchell** [comment]
I should add it will only notify if you have notification set up on that status in the admin.

**Comment by roydeanjr** [comment]
Can you see this?
[cid:c67f870b-6da9-4530-942b-924a091c7627]

Cheers,

RoyDean Leighton, Jr.
https://facebook.com/RDQBBQ

https://rdqbbq.com<http://rdqbbq.com/>

https://instagram.com/RDQBBQ

<https://yelp.com/rdq-houston>https://www.yelp.com/biz/rdq-houston
https://twitter.com/RDQBBQ

________________________________

**Comment by roydeanjr** [comment]
Yes, I tested it and it does not automagically send an email. I believe Sam uses that to set the default that shows in the pop-up when changing the status of an order. It does not send automagically, but sets the "Notify customer" toggle so that when the Save button is clicked, the system will send an email. Maybe not, but I think that is how it is used.


Cheers,

RoyDean Leighton, Jr.
https://facebook.com/RDQBBQ

https://rdqbbq.com<http://rdqbbq.com/>

https://instagram.com/RDQBBQ

<https://yelp.com/rdq-houston>https://www.yelp.com/biz/rdq-houston
https://twitter.com/RDQBBQ

________________________________

**Comment by ryanmitchell** [comment]
Still no attachment - you need to add it through github directly. 

I’ll check with Sam about notifications.

**Comment by ryanmitchell** [comment]
I've added the notify_customer option which should send the email when status is updated

**Comment by roydeanjr** [comment]
This is what I had in mind. (I also prefer the expanded width of the location pull-down as my location names are long and wrap in the option list. This makes it a bit cumbersome with long enabled lists. I will test the email option directly.
image

**Comment by ryanmitchell** [comment]
I’ve pushed an update to make the location selector full width - may as well as there is nothing else there.

I don’t think the background colour looks good - it will make text unreadable too. Are you not getting the right border colour on each of the order boxes?

**Comment by roydeanjr** [comment]
I am getting the right border. I am green/red color blind, so it looked black until I focused on it and did notice that it was the color of the status.

If the text is not black when the status is set, then it is more readable. I understand what you are saying, my request is simply based on my experience and that I did not notice the color until you pointed it out. 

I do also see that the button of the current status is "pressed" or not the color set in the status table.

How about the option of styling the status word displayed on each card? Here are some options:
This is _class="card-subtitle mt-1 mb-2" style="background-color:`<?= $order->status_color; ?>`"_ but I could not figure our how to make the text white.
image

This is _class="label label-default" style="background-color:`<?= $order->status_color; ?>`"_ and here I could not get the size bigger. I'm just not familiar with the styling of the classes yet.
image

I also tightened up the whitespace between by eliminating the _`<p><br /></p>`_ from lines 47-49 and `</p> <p>` from lines 65-67.

What do you think?

**Comment by sitsegypt** [comment]
I am testing the latest commit but I faced the below issue

Annotation 2020-08-31 125116
Annotation 2020-08-31 1251161
Annotation 2020-08-31 1251162

**Comment by roydeanjr** [comment]
And, my testing did not result in an email being sent.

**Comment by ryanmitchell** [comment]
I've pushed some final changes. 

I'm going to have to draw a line here as this is unpaid work - if you want to make more changes and get my opinion then feel free to add a new PR. I'm going to merge and close this one.

**Comment by roydeanjr** [comment]
Your help is much appreciated! Where can we send money?

**Comment by ryanmitchell** [comment]
Oh no that’s not what I meant :)
I need to go back to my day job!

Send Sam some money or sponsor the project - he deserves it more than me.

**Comment by roydeanjr** [comment]
Yes, I understand. And I need some sleep!

**Pull request merged**
